import { Apartment } from "./types";

export const apartmentsData: Apartment[] = [
  {
    id: 1,
    name: "Grand Kamala Lagoon",
    location: "Bekasi Selatan",
    price: 3500000,
    period: "bulan",
    rating: 4.8,
    reviews: 120,
    type: "2BR",
    furnish: "Full Furnished",
    provider: "Kosku Managed",
    image: "/images/hero/banner.jpg",
    isVerified: true,
    isPromo: true,
    sisaKamar: 2,
    facilities: ["wifi", "pool", "gym", "ac"],
  },
  {
    id: 2,
    name: "Bassura City",
    location: "Jatinegara, Jaktim",
    price: 4200000,
    period: "bulan",
    rating: 4.6,
    reviews: 85,
    type: "2BR",
    furnish: "Semi Furnished",
    provider: "Direct Owner",
    image: "/images/hero/banner.jpg",
    isVerified: true,
    sisaKamar: 5,
    facilities: ["wifi", "tv", "ac", "kitchen"],
  },
  {
    id: 3,
    name: "Kalibata City",
    location: "Pancoran, Jaksel",
    price: 3500000, 
    period: "bulan",
    rating: 4.5,
    reviews: 200,
    type: "Studio",
    furnish: "Full Furnished",
    provider: "Kosku Managed",
    image: "/images/hero/banner.jpg",
    isVerified: false,
    sisaKamar: 1,
    facilities: ["ac", "kitchen", "tv"],
  },
  {
    id: 4,
    name: "Podomoro Golf View",
    location: "Cimanggis, Depok",
    price: 3100000,
    period: "bulan",
    rating: 4.9,
    reviews: 45,
    type: "Studio",
    furnish: "Unfurnished",
    provider: "Direct Owner",
    image: "/images/hero/banner.jpg",
    isVerified: true,
    sisaKamar: 10,
    facilities: ["wifi", "pool", "view"],
  },
  {
    id: 5,
    name: "Margonda Residence 5",
    location: "Beji, Depok",
    price: 2500000,
    period: "bulan",
    rating: 4.7,
    reviews: 150,
    type: "Studio",
    furnish: "Full Furnished",
    provider: "Kosku Managed",
    image: "/images/hero/banner.jpg",
    isVerified: true,
    sisaKamar: 0,
    facilities: ["wifi", "desk", "ac"],
  },
  {
    id: 6,
    name: "Thamrin Residence",
    location: "Tanah Abang, Jakpus",
    price: 15000000,
    period: "bulan",
    rating: 5.0,
    reviews: 32,
    type: "3BR",
    furnish: "Full Furnished",
    provider: "Direct Owner",
    image: "/images/hero/banner.jpg",
    isVerified: true,
    sisaKamar: 3,
    facilities: ["wifi", "pool", "gym", "bath"],
  },
];